### ISSUE TITLE
What is the goal for aligning the keypoints?

### ISSUE THREAD

**Issue by zzw1123** [liruilong940607/Pose2Seg#4]
Hi, thanks for your contribution!
I have a question that why should we align all the keypoints? For ROI align, the features must be input to fully connected layer so the size of them should be the same. But in the segmentation task, there is no fc layer and I cannot figure out the function of affine-align operation.

**Comment by liruilong940607** [comment]
Thanks for your attention!

An alignment brings several benefits:
(1) Human in the image have wide range of size. An aligned size and centralisation makes segmentation network easy to learn.
(2) Alignment reduce the calculation. Otherwise, to do instance segmentation, we will need to process whole image for each instance. It will cost a lot more gpu memory as well as calculation.
